"""TypeScript type generation commands."""

import click
from pathlib import Path
from rich.console import Console

console = Console()


@click.group()
def types_group():
    """Type generation commands."""
    pass


@types_group.command('typescript')
@click.option('--output', type=click.Path(), default='types/database.ts', help='Output file path')
@click.option('--project', help='Project slug (overrides default)')
@click.option('--local', is_flag=True, help='Generate from local database')
@click.pass_context
def generate_typescript(ctx, output, project, local):
    """Generate TypeScript types from database schema."""
    try:
        api = ctx.obj['api']
        config = ctx.obj['config']
        project_slug = project or config.get_default_project()
        
        if not project_slug:
            console.print("[red]Error:[/red] No project specified. Use --project or set default project.")
            raise click.Abort()
        
        if local:
            console.print("[yellow]Local database type generation not yet implemented[/yellow]")
            return
        
        # Get schema
        schema = api.get_schema(project_slug)
        tables = schema.get('tables', [])
        
        if not tables:
            console.print("[yellow]No tables found[/yellow]")
            return
        
        # Generate TypeScript interfaces
        output_path = Path(output)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        
        with open(output_path, 'w') as f:
            f.write("// Auto-generated TypeScript types from WoWSQL database schema\n")
            f.write("// Do not edit this file manually\n\n")
            
            for table in tables:
                table_name = table.get('name', '')
                columns = table.get('columns', [])
                
                # Convert table name to TypeScript interface name
                interface_name = ''.join(word.capitalize() for word in table_name.split('_'))
                
                f.write(f"export interface {interface_name} {{\n")
                
                for col in columns:
                    col_name = col.get('name', '')
                    col_type = col.get('type', '')
                    nullable = col.get('nullable', False)
                    
                    # Map PostgreSQL types to TypeScript types
                    ts_type = _pg_to_typescript(col_type)
                    if nullable:
                        ts_type += " | null"
                    
                    f.write(f"  {col_name}: {ts_type};\n")
                
                f.write("}\n\n")
        
        console.print(f"[green]✓[/green] Generated TypeScript types: {output_path}")
        console.print(f"  {len(tables)} table(s) processed")
    except Exception as e:
        console.print(f"[red]Error:[/red] {e}")
        raise click.Abort()


def _pg_to_typescript(pg_type: str) -> str:
    """Convert PostgreSQL type to TypeScript type."""
    t = pg_type.lower().strip()

    # Integer types
    if t in ('integer', 'int', 'int4', 'int2', 'smallint', 'bigint', 'int8',
             'serial', 'bigserial', 'smallserial'):
        return 'number'
    # Floating point / numeric
    if t in ('real', 'float4', 'float8', 'double precision', 'numeric', 'decimal'):
        return 'number'
    if t.startswith('numeric') or t.startswith('decimal'):
        return 'number'
    # Boolean
    if t == 'boolean' or t == 'bool':
        return 'boolean'
    # Date / time
    if t in ('date', 'time', 'timetz', 'timestamp', 'timestamptz',
             'time without time zone', 'time with time zone',
             'timestamp without time zone', 'timestamp with time zone',
             'interval'):
        return 'Date'
    # JSON
    if t in ('json', 'jsonb'):
        return 'any'
    # UUID
    if t == 'uuid':
        return 'string'
    # Array types
    if t.endswith('[]') or t.startswith('array'):
        return 'any[]'
    # Binary
    if t == 'bytea':
        return 'Buffer'
    # Default: string covers text, varchar, char, name, citext, etc.
    return 'string'

